micronaut:
  router:
    static-resources:
      default:
        enabled: true
        paths: file:ui
  server:
    cors:
      # only needed when doing front end dev on port 3000
      enabled: ${CORS_ENABLED:true}
      configurations:
        all:
          allowedOrigins:
            - http://localhost:3000
endpoints:
  health:
    #details-visible: ANONYMOUS

backend:
  tag:
    name: ${SCHEDULER_TAG:scheduler-enabled}
    value: "true"
  zoneId: ${ZONE_ID:UTC}
  ssmPath: ${SSM_PATH:/scheduler/timestamp}
  useMultiAz: ${USE_MULTI_AZ:false}
  weekdayStart: ${WEEKDAY_START:}
  uptimeWindow: ${UPTIME_WINDOW:10}
